version: '3'

services:
    mysql:
        image: mysql:latest
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: thebestpasswordintheentireuniversedude
            MYSQL_DATABASE: wordpress
            MYSQL_USER: root
    lfi:
        build: .
        depends_on:
            - mysql
        links:
            - "mysql:themysql"
        ports:
            - "80:80"
        environment:
            WORDPRESS_DB_HOST: themysql
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: thebestpasswordintheentireuniversedude
